main: net.minegusta.mgcommandcooldown.main.Main
name: MGCommandCooldown
version: ${project.version}
author: janie177
commands:
   mgccreload:
      description: Reload all the cooldowns from the config.
      usage: /MGCCReload
      permission: minegusta.cooldown.reload
      default: op

permissions:
  minegusta.cooldown.bypass:
    default: op
    description: lets you bypass cooldowns.
  minegusta.warmup.bypass:
    default: op
    description: lets you bypass warmups.